// examples/notes-client-svelte/src/components/CreateNoteForm.svelte
<script lang="ts">
  import type { NoteRecord } from "../types.js";
  import { COLORS, COLOR_HEX, FONT_FAMILIES } from "../types.js";

  type CreateData = Omit<
    NoteRecord,
    "recordId" | "createdAt" | "updatedAt" | "revisionCount" | "userId"
  >;

  let { onSubmit, onCancel }: { onSubmit: (data: CreateData) => void; onCancel: () => void } =
    $props();

  let title = $state("");
  let contents = $state("");
  let color = $state<string | null>(null);
  let category = $state("");
  let fontFamily = $state<string | null>(null);

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    onSubmit({ title, contents, color, category: category || null, fontFamily, isDeleted: false });
  }

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === e.currentTarget) onCancel();
  }

  const colorOptions = [null, ...COLORS] as const;
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
  onclick={handleOverlayClick}
  style="position: fixed; inset: 0; background: rgba(15,23,42,0.5); display: flex; align-items: center; justify-content: center; z-index: 50; padding: 16px;"
>
  <form
    onsubmit={handleSubmit}
    style="background: #fff; border-radius: 16px; padding: 24px; width: 100%; max-width: 480px; display: flex; flex-direction: column; gap: 16px; box-shadow: 0 20px 60px rgba(0,0,0,0.2);"
  >
    <h2 style="font-size: 18px; font-weight: 700; color: #1e293b;">New note</h2>

    <div style="display: flex; flex-direction: column; gap: 4px;">
      <label for="note-title" style="font-size: 13px; font-weight: 600; color: #475569;">Title</label>
      <input
        id="note-title"
        bind:value={title}
        placeholder="Note title"
        required
        style="width: 100%; padding: 8px 12px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 14px; outline: none; font-family: inherit;"
      />
    </div>

    <div style="display: flex; flex-direction: column; gap: 4px;">
      <label for="note-contents" style="font-size: 13px; font-weight: 600; color: #475569;">Contents</label>
      <textarea
        id="note-contents"
        bind:value={contents}
        placeholder="Write something…"
        style="width: 100%; padding: 8px 12px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 14px; outline: none; font-family: inherit; min-height: 100px; resize: vertical;"
      ></textarea>
    </div>

    <div style="display: flex; gap: 12px;">
      <!-- Color -->
      <div style="flex: 1; display: flex; flex-direction: column; gap: 4px;">
        <!-- svelte-ignore a11y_label_has_associated_control -->
        <label style="font-size: 13px; font-weight: 600; color: #475569;">Color</label>
        <div style="display: flex; gap: 8px; flex-wrap: wrap;">
          {#each colorOptions as c (c ?? "none")}
            <button
              type="button"
              onclick={() => (color = c ?? null)}
              title={c ?? "none"}
              style="width: 28px; height: 28px; border-radius: 50%; border: {color === (c ?? null)
                ? '3px solid #1e293b'
                : '2px solid #e2e8f0'}; background: {c ? (COLOR_HEX[c] ?? '#e2e8f0') : '#e2e8f0'}; cursor: pointer;"
            ></button>
          {/each}
        </div>
      </div>

      <!-- Category -->
      <div style="flex: 1; display: flex; flex-direction: column; gap: 4px;">
        <label for="note-category" style="font-size: 13px; font-weight: 600; color: #475569;">Category</label>
        <input
          id="note-category"
          bind:value={category}
          placeholder="e.g. work, ideas"
          style="width: 100%; padding: 8px 12px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 14px; outline: none; font-family: inherit;"
        />
      </div>
    </div>

    <!-- Font family -->
    <div style="display: flex; flex-direction: column; gap: 4px;">
      <label for="note-font" style="font-size: 13px; font-weight: 600; color: #475569;">Font family</label>
      <select
        id="note-font"
        value={fontFamily ?? ""}
        onchange={(e) => (fontFamily = (e.currentTarget as HTMLSelectElement).value || null)}
        style="width: 100%; padding: 8px 12px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 14px; outline: none; font-family: inherit;"
      >
        <option value="">Default</option>
        {#each FONT_FAMILIES as f (f)}
          <option value={f} style="font-family: {f};">{f}</option>
        {/each}
      </select>
    </div>

    <!-- Actions -->
    <div style="display: flex; gap: 8px; justify-content: flex-end;">
      <button
        type="button"
        onclick={onCancel}
        style="padding: 8px 20px; border: 1px solid #e2e8f0; border-radius: 8px; background: #fff; cursor: pointer; font-size: 14px;"
      >
        Cancel
      </button>
      <button
        type="submit"
        style="padding: 8px 20px; border: none; border-radius: 8px; background: #3b82f6; color: #fff; cursor: pointer; font-weight: 600; font-size: 14px;"
      >
        Create
      </button>
    </div>
  </form>
</div>

// examples/notes-client/src/components/CreateNoteForm.tsx
import { useState } from "react";
import type { NoteRecord } from "../types.js";
import { COLORS, COLOR_HEX, FONT_FAMILIES } from "../types.js";

type CreateData = Omit<NoteRecord, "recordId" | "createdAt" | "updatedAt" | "revisionCount" | "userId">;

interface Props {
  onSubmit: (data: CreateData) => void;
  onCancel: () => void;
}

export default function CreateNoteForm({ onSubmit, onCancel }: Props) {
  const [title, setTitle] = useState("");
  const [contents, setContents] = useState("");
  const [color, setColor] = useState<string | null>(null);
  const [category, setCategory] = useState("");
  const [fontFamily, setFontFamily] = useState<string | null>(null);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    onSubmit({ title, contents, color, category: category || null, fontFamily, isDeleted: false });
  }

  const overlay: React.CSSProperties = {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: 16,
  };

  const modal: React.CSSProperties = {
    background: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 480,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
  };

  const label: React.CSSProperties = { fontSize: 13, fontWeight: 600, color: "#475569" };

  const input: React.CSSProperties = {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    fontSize: 14,
    outline: "none",
    fontFamily: "inherit",
  };

  return (
    <div style={overlay} onClick={(e) => e.target === e.currentTarget && onCancel()}>
      <form style={modal} onSubmit={handleSubmit}>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: "#1e293b" }}>New note</h2>

        <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
          <label style={label}>Title</label>
          <input
            style={input}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Note title"
            required
          />
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
          <label style={label}>Contents</label>
          <textarea
            style={{ ...input, minHeight: 100, resize: "vertical" }}
            value={contents}
            onChange={(e) => setContents(e.target.value)}
            placeholder="Write something…"
          />
        </div>

        <div style={{ display: "flex", gap: 12 }}>
          {/* Color */}
          <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 4 }}>
            <label style={label}>Color</label>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {[null, ...COLORS].map((c) => (
                <button
                  key={c ?? "none"}
                  type="button"
                  onClick={() => setColor(c)}
                  title={c ?? "none"}
                  style={{
                    width: 28,
                    height: 28,
                    borderRadius: "50%",
                    border: color === c ? "3px solid #1e293b" : "2px solid #e2e8f0",
                    background: c ? COLOR_HEX[c] : "#e2e8f0",
                    cursor: "pointer",
                  }}
                />
              ))}
            </div>
          </div>

          {/* Category */}
          <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 4 }}>
            <label style={label}>Category</label>
            <input
              style={input}
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              placeholder="e.g. work, ideas"
            />
          </div>
        </div>

        {/* Font family */}
        <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
          <label style={label}>Font family</label>
          <select
            style={input}
            value={fontFamily ?? ""}
            onChange={(e) => setFontFamily(e.target.value || null)}
          >
            <option value="">Default</option>
            {FONT_FAMILIES.map((f) => (
              <option key={f} value={f} style={{ fontFamily: f }}>
                {f}
              </option>
            ))}
          </select>
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
          <button
            type="button"
            onClick={onCancel}
            style={{
              padding: "8px 20px",
              border: "1px solid #e2e8f0",
              borderRadius: 8,
              background: "#fff",
              cursor: "pointer",
              fontSize: 14,
            }}
          >
            Cancel
          </button>
          <button
            type="submit"
            style={{
              padding: "8px 20px",
              border: "none",
              borderRadius: 8,
              background: "#3b82f6",
              color: "#fff",
              cursor: "pointer",
              fontWeight: 600,
              fontSize: 14,
            }}
          >
            Create
          </button>
        </div>
      </form>
    </div>
  );
}
